In [36]:
import os
a=os.listdir(".")
a

['.DS_Store',
 'dataMining',
 'maaz',
 'face',
 'Untitled.ipynb',
 'mom-.csv',
 'mom .xlsx',
 '.ipynb_checkpoints',
 'hello',
 'untitled']

In [37]:
import pandas as pd

In [38]:
a = pd.read_csv("mom-.csv")

In [39]:
a

    force (KN) change in length(mm)                    stress(MPa)    strain
0          0.0                    0                              0         0
1          7.6                 0.02                         76.051    0.0004
2         14.9                 0.04                          149.1    0.0008
3         22.2                 0.06                        222.149    0.0012
4         28.6                 0.08                        286.192    0.0016
5         29.9                  0.1                        299.201     0.002
6         30.6                 0.12                        306.206    0.0024
7         32.0                 0.16                        320.215    0.0032
8         33.0                  0.2                        330.222     0.004
9         33.3                 0.24                        333.224    0.0048
10        36.8                  0.5                        368.247      0.01
11        41.0                    1                        410.276      0.02
12        43.8                  1.5                        438.295      0.03
13        45.8                    2                        458.308      0.04
14        48.3                    3                        483.325      0.06
15        49.7                    4                        497.334      0.08
16        50.4                    5                        504.339       0.1
17        50.7                    6                        507.341      0.12
18        50.4                    7                        504.339      0.14
19        50.0                    8                        500.336      0.16
20        49.7                    9                        497.334      0.18
21        47.9                   10                        479.322       0.2
22        45.1             fracture  636.26(TRUE)    451.30(IDEAL)  fracture

In [40]:
a = pd.read_csv("mom-.csv",index_col = ["force (KN)","stress(MPa)"])

In [41]:
a

                                         change in length(mm)    strain
force (KN) stress(MPa)
0.0        0                                                0         0
7.6        76.051                                        0.02    0.0004
14.9       149.1                                         0.04    0.0008
22.2       222.149                                       0.06    0.0012
28.6       286.192                                       0.08    0.0016
29.9       299.201                                        0.1     0.002
30.6       306.206                                       0.12    0.0024
32.0       320.215                                       0.16    0.0032
33.0       330.222                                        0.2     0.004
33.3       333.224                                       0.24    0.0048
36.8       368.247                                        0.5      0.01
41.0       410.276                                          1      0.02
43.8       438.295                                        1.5      0.03
45.8       458.308                                          2      0.04
48.3       483.325                                          3      0.06
49.7       497.334                                          4      0.08
50.4       504.339                                          5       0.1
50.7       507.341                                          6      0.12
50.4       504.339                                          7      0.14
50.0       500.336                                          8      0.16
49.7       497.334                                          9      0.18
47.9       479.322                                         10       0.2
45.1       636.26(TRUE)    451.30(IDEAL)             fracture  fracture

In [44]:
import numpy as np
a = pd.read_csv("mom-.csv",na_values= [0]) # where there is zero then it will put Nan

In [45]:
a

    force (KN) change in length(mm)                    stress(MPa)    strain
0          NaN                  NaN                            NaN       NaN
1          7.6                 0.02                         76.051    0.0004
2         14.9                 0.04                          149.1    0.0008
3         22.2                 0.06                        222.149    0.0012
4         28.6                 0.08                        286.192    0.0016
5         29.9                  0.1                        299.201     0.002
6         30.6                 0.12                        306.206    0.0024
7         32.0                 0.16                        320.215    0.0032
8         33.0                  0.2                        330.222     0.004
9         33.3                 0.24                        333.224    0.0048
10        36.8                  0.5                        368.247      0.01
11        41.0                    1                        410.276      0.02
12        43.8                  1.5                        438.295      0.03
13        45.8                    2                        458.308      0.04
14        48.3                    3                        483.325      0.06
15        49.7                    4                        497.334      0.08
16        50.4                    5                        504.339       0.1
17        50.7                    6                        507.341      0.12
18        50.4                    7                        504.339      0.14
19        50.0                    8                        500.336      0.16
20        49.7                    9                        497.334      0.18
21        47.9                   10                        479.322       0.2
22        45.1             fracture  636.26(TRUE)    451.30(IDEAL)  fracture

In [46]:
a = pd.read_csv("mom-.csv",nrows=22)
a

    force (KN)  change in length(mm)  stress(MPa)  strain
0          0.0                  0.00        0.000  0.0000
1          7.6                  0.02       76.051  0.0004
2         14.9                  0.04      149.100  0.0008
3         22.2                  0.06      222.149  0.0012
4         28.6                  0.08      286.192  0.0016
5         29.9                  0.10      299.201  0.0020
6         30.6                  0.12      306.206  0.0024
7         32.0                  0.16      320.215  0.0032
8         33.0                  0.20      330.222  0.0040
9         33.3                  0.24      333.224  0.0048
10        36.8                  0.50      368.247  0.0100
11        41.0                  1.00      410.276  0.0200
12        43.8                  1.50      438.295  0.0300
13        45.8                  2.00      458.308  0.0400
14        48.3                  3.00      483.325  0.0600
15        49.7                  4.00      497.334  0.0800
16        50.4                  5.00      504.339  0.1000
17        50.7                  6.00      507.341  0.1200
18        50.4                  7.00      504.339  0.1400
19        50.0                  8.00      500.336  0.1600
20        49.7                  9.00      497.334  0.1800
21        47.9                 10.00      479.322  0.2000

In [49]:
chunkread= pd.read_csv("mom-.csv",chunksize=7)

In [50]:
chunkread

In [51]:
for i in chunkread:
    print(i)

   force (KN)  change in length(mm)  stress(MPa)  strain
0         0.0                  0.00        0.000  0.0000
1         7.6                  0.02       76.051  0.0004
2        14.9                  0.04      149.100  0.0008
3        22.2                  0.06      222.149  0.0012
4        28.6                  0.08      286.192  0.0016
5        29.9                  0.10      299.201  0.0020
6        30.6                  0.12      306.206  0.0024
    force (KN)  change in length(mm)  stress(MPa)  strain
7         32.0                  0.16      320.215  0.0032
8         33.0                  0.20      330.222  0.0040
9         33.3                  0.24      333.224  0.0048
10        36.8                  0.50      368.247  0.0100
11        41.0                  1.00      410.276  0.0200
12        43.8                  1.50      438.295  0.0300
13        45.8                  2.00      458.308  0.0400
    force (KN)  change in length(mm)  stress(MPa)  strain
14        48.3                     3      483.325    0.06
15        49.7                     4      497.334    0.08
16        50.4                     5      504.339    0.10
17        50.7                     6      507.341    0.12
18        50.4                     7      504.339    0.14
19        50.0                     8      500.336    0.16
20        49.7                     9      497.334    0.18
    force (KN) change in length(mm)                    stress(MPa)    strain
21        47.9                   10                        479.322       0.2
22        45.1             fracture  636.26(TRUE)    451.30(IDEAL)  fracture

In [53]:
import csv
f=open('mom-.csv')
reader = csv.reader(f)
reader

In [54]:
for i in reader:
    print(i)

['force (KN)', 'change in length(mm)', 'stress(MPa)', 'strain']
['0', '0', '0', '0']
['7.6', '0.02', '76.051', '0.0004']
['14.9', '0.04', '149.1', '0.0008']
['22.2', '0.06', '222.149', '0.0012']
['28.6', '0.08', '286.192', '0.0016']
['29.9', '0.1', '299.201', '0.002']
['30.6', '0.12', '306.206', '0.0024']
['32', '0.16', '320.215', '0.0032']
['33', '0.2', '330.222', '0.004']
['33.3', '0.24', '333.224', '0.0048']
['36.8', '0.5', '368.247', '0.01']
['41', '1', '410.276', '0.02']
['43.8', '1.5', '438.295', '0.03']
['45.8', '2', '458.308', '0.04']
['48.3', '3', '483.325', '0.06']
['49.7', '4', '497.334', '0.08']
['50.4', '5', '504.339', '0.1']
['50.7', '6', '507.341', '0.12']
['50.4', '7', '504.339', '0.14']
['50', '8', '500.336', '0.16']
['49.7', '9', '497.334', '0.18']
['47.9', '10', '479.322', '0.2']
['45.1', 'fracture', '636.26(TRUE)    451.30(IDEAL)', 'fracture']

In [56]:
import csv
f=open('mom-.csv')
reader = csv.reader(f)
reader=list(reader)
reader

[['force (KN)', 'change in length(mm)', 'stress(MPa)', 'strain'],
 ['0', '0', '0', '0'],
 ['7.6', '0.02', '76.051', '0.0004'],
 ['14.9', '0.04', '149.1', '0.0008'],
 ['22.2', '0.06', '222.149', '0.0012'],
 ['28.6', '0.08', '286.192', '0.0016'],
 ['29.9', '0.1', '299.201', '0.002'],
 ['30.6', '0.12', '306.206', '0.0024'],
 ['32', '0.16', '320.215', '0.0032'],
 ['33', '0.2', '330.222', '0.004'],
 ['33.3', '0.24', '333.224', '0.0048'],
 ['36.8', '0.5', '368.247', '0.01'],
 ['41', '1', '410.276', '0.02'],
 ['43.8', '1.5', '438.295', '0.03'],
 ['45.8', '2', '458.308', '0.04'],
 ['48.3', '3', '483.325', '0.06'],
 ['49.7', '4', '497.334', '0.08'],
 ['50.4', '5', '504.339', '0.1'],
 ['50.7', '6', '507.341', '0.12'],
 ['50.4', '7', '504.339', '0.14'],
 ['50', '8', '500.336', '0.16'],
 ['49.7', '9', '497.334', '0.18'],
 ['47.9', '10', '479.322', '0.2'],
 ['45.1', 'fracture', '636.26(TRUE)    451.30(IDEAL)', 'fracture']]

In [58]:
header,values = reader[0],reader[1:]
data_dict = {h:v for h ,v in zip(header,zip(*values))}

In [59]:
data_dict

{'force (KN)': ('0',
  '7.6',
  '14.9',
  '22.2',
  '28.6',
  '29.9',
  '30.6',
  '32',
  '33',
  '33.3',
  '36.8',
  '41',
  '43.8',
  '45.8',
  '48.3',
  '49.7',
  '50.4',
  '50.7',
  '50.4',
  '50',
  '49.7',
  '47.9',
  '45.1'),
 'change in length(mm)': ('0',
  '0.02',
  '0.04',
  '0.06',
  '0.08',
  '0.1',
  '0.12',
  '0.16',
  '0.2',
  '0.24',
  '0.5',
  '1',
  '1.5',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  'fracture'),
 'stress(MPa)': ('0',
  '76.051',
  '149.1',
  '222.149',
  '286.192',
  '299.201',
  '306.206',
  '320.215',
  '330.222',
  '333.224',
  '368.247',
  '410.276',
  '438.295',
  '458.308',
  '483.325',
  '497.334',
  '504.339',
  '507.341',
  '504.339',
  '500.336',
  '497.334',
  '479.322',
  '636.26(TRUE)    451.30(IDEAL)'),
 'strain': ('0',
  '0.0004',
  '0.0008',
  '0.0012',
  '0.0016',
  '0.002',
  '0.0024',
  '0.0032',
  '0.004',
  '0.0048',
  '0.01',
  '0.02',
  '0.03',
  '0.04',
  '0.06',
  '0.08',
  '0.1',
  '0.12',
  '0.14',
  '0.16',
  '0.18',
  '0.2',
  'fracture')}

In [1]:
obj = """
    {"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
                  {"name": "Katie", "age": 38,
                   "pets": ["Sixes", "Stache", "Cisco"]}]
} """

In [2]:
import json

In [3]:
result = json.loads(obj)

In [4]:
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [6]:
asjson = json.dumps(result)

In [7]:
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'